sudo: required
services: 
  - docker

before_install:
  - docker build -t yuankunluo/docker-react-test -f Dockerfile .

script:
  - docker run -e CI=true yuankunluo/docker-react-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-005860480826"
  bucket_path: "docker-react-test"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
